### ISSUE TITLE
패스파인더 아스트라 뺀 dpm 확인중 오류

### ISSUE THREAD

**Issue by jml845854** [oleneyl/maplestory_dpm_calc#487]
return(CardinalBlast,
                [globalSkill.maple_heros(chtr.level, combat_level=self.combat), globalSkill.useful_wind_booster(), globalSkill.useful_combat_orders(),
                    RelicCharge, AncientBowBooster, CurseTolerance, CurseTransition, SharpEyes,
                    RelicEvolution, EpicAdventure,
                    AncientGuidance, AdditionalTransition,globalSkill.MapleHeroes2Wrapper(vEhc, 0, 0, chtr.level, self.combat), CriticalReinforce,
                    globalSkill.soul_contract()] +\
                [RelicUnboundDischarge, AncientAstraHolder, TripleImpact, EdgeOfResonance,
                        ComboAssultHolder, UltimateBlast, SplitMistel, CardinalTransition] +\
                [Evolve, Raven, GuidedArrow, RavenTempest, ObsidionBarrierBlast, MirrorBreak, MirrorSpider] +\
                [] +\
                [CardinalBlast])

패스파인더 코드 중   에인션트 아스트라 딜을 빼서 보고 싶어서 빼서 돌렸는데 오류가 발생합니다.
에인션트 아스트라 뿐만아니라 
ComboAssultHolder, UltimateBlast, SplitMistel, CardinalTransition 
Evolve,  RavenTempest 도 빼니 오류가 납니다

오류 내용 입니다.
python test.py --job 패스파인더 --ulevel 8000 --stat
Traceback (most recent call last):
  File "test.py", line 59, in dpm
    statistics=args.stat or args.log)
  File "C:\Users\owner\Desktop\maplestory_dpm_calc-master (1)\maplestory_dpm_calc-master\dpmModule\util\dpmgenerator.py", line 49, in get_dpm
    control.start_simulation(self.runtime)
  File "C:\Users\owner\Desktop\maplestory_dpm_calc-master (1)\maplestory_dpm_calc-master\dpmModule\kernel\core.py", line 1688, in start_simulation
    self.scheduler.initialize(time)
  File "C:\Users\owner\Desktop\maplestory_dpm_calc-master (1)\maplestory_dpm_calc-master\dpmModule\kernel\policy.py", line 158, in initialize
    for wrp in rule.get_related_elements(self.graph):
  File "C:\Users\owner\Desktop\maplestory_dpm_calc-master (1)\maplestory_dpm_calc-master\dpmModule\execution\rules.py", line 98, in get_related_elements
    return [reference_graph.get_element(self.target_element)]
  File "C:\Users\owner\Desktop\maplestory_dpm_calc-master (1)\maplestory_dpm_calc-master\dpmModule\kernel\policy.py", line 29, in get_element
    check with graph.get_storage()''')
KeyError: 'No element name 에인션트 아스트라 exist. Check your graph configuration, or\n            check with graph.get_storage()'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 69, in <module>
    test()
  File "test.py", line 34, in test
    dpm(args)
  File "test.py", line 63, in dpm
    print(jobname, dpm)
UnboundLocalError: local variable 'dpm' referenced before assignment

**Comment by jml845854** [comment]
호영에서도 Misaeng 을 빼고 돌렸을때 같은 오류가 발생하는것 같습니다.
필연적인 오류인건가요?

그리고 Clone_Rampage_Attack,Talisman_Clone_Attack,
분신부와 분신난무를 빼고 코드를 돌렸을때 0.1% 점유율이 나오는데 왜 사용이 되는 걸까요 ㅠ

분신 뿐 아니라 천지인 환영 Elemental_Clone_Active, Elemental_Clone_Passive 도 점유율이 나오고 있습니다

**Comment by icepeng** [comment]
특정 스킬을 비활성화하고 싶으시면 `get_ruleset()` 쪽에서 DisableRule을 걸어주는게 낫습니다.

추가타류 스킬은 쿨타임이 돌아와있으면 onAfter으로 이어지는 식으로 사용되고 있어서 조금 복잡한데... 잠시 확인해보겠습니다.

**Comment by icepeng** [comment]
아마 아스트라는 이미 DisableRule이 걸려서 안쓰고 있을겁니다.

**Comment by icepeng** [comment]
추가타류 스킬 사용을 막으려면

https://github.com/oleneyl/maplestory_dpm_calc/blob/b7bead5c65e69e0afe2ac13c131f890f66f282c2/dpmModule/jobs/hoyoung.py#L361-L363

이쪽에서 스킬을 제거하는게 편할거 같습니다.

**Comment by oleneyl** [comment]
Rule이 참조하고 있는 스킬을 반환하지 않아서 그렇습니다. DisableRule을 ruleset에 추가해주시면 원하시는 방식으로 작동할겁니다.
